CREATE TABLE IF NOT EXISTS contact (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,
    mobile VARCHAR(32) NOT NULL,
    department VARCHAR(128),
    title VARCHAR(128),
    status VARCHAR(32) DEFAULT '在岗',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contact_group (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    owner_dept VARCHAR(128),
    member_count INT DEFAULT 0,
    tags VARCHAR(512),
    last_sync_time DATETIME,
    status VARCHAR(32) DEFAULT '启用',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS briefing_template (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    category VARCHAR(64) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(32) DEFAULT '启用中',
    owner VARCHAR(64),
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS briefing (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(128) NOT NULL,
    content TEXT NOT NULL,
    template_id BIGINT,
    status VARCHAR(32) DEFAULT '待审核',
    channel VARCHAR(64),
    author VARCHAR(64),
    version VARCHAR(32),
    audience VARCHAR(255),
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS send_task (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(200) NOT NULL,
    channel VARCHAR(64) NOT NULL,
    planned_send_time DATETIME,
    status VARCHAR(32) NOT NULL,
    recipient_count INT DEFAULT 0,
    creator VARCHAR(64),
    success_rate VARCHAR(32),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
